apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  destination:
    name: management
    namespace: crossplane-system
  project: default
  source:
    path: apps/argocd/
    repoURL: https://github.com/Mathod95/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true