apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    name: k8s-pre-production
    namespace: crossplane-system
  project: preprod
  source:
    repoURL: "https://github.com/Mathod95/argocd.git"
    targetRevision: HEAD
    path: "apps/crossplane/"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true