apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: production
spec:
  forProvider:
    config:
      tlsClientConfig:
        insecure: true
    name: production
    server: https://192.168.1.39:8444
  providerConfigRef:
    name: argocd-provider